### ISSUE TITLE
Reducing the file size

### ISSUE THREAD

**Issue by jsvine** [declanrjb/dlp-inmate-complaints#1]
The [current draft file](https://drive.google.com/file/d/1kFyrQgJftoRrZSBT6YhLU7bwp8ba561z/view?usp=drive_link) is 516MB in size, which I worry hampers data accessibility. Of course, any exercise in expanding codes to full descriptions will require some additional storage, but I'm hoping we can find some middle-ground.

Even better if we can get the file(s) under GitHub's 100MB-per-file limit. (And Google Sheets' [apparent] 5-million-cell limit.)

Some possible strategies:

- Revert the expansion of the status reason (`STAT_RSON_1`, `STAT_RSON_2`, `STAT_RSON_3`, `STAT_RSON_4`, `STAT_RSON_5`) columns. Given how wordy the descriptions are, I think it's fair to have folks cross-reference them in the lookup table.

- Split the file into three time periods, based on filing date: `2000–2009`, `2010-19`, and `2020-2024`. Although this adds an extra step for folks who want to examine the full time period, it makes the dataset less bulky for folks mostly interested in recent years.

- Consider removing the facility-code columns; if someone wants to use those codes, they can use the raw data.

Any other ideas come to mind?

**Comment by jsvine** [comment]
(If removing the facility code columns, we'll still need to handle the cases where the code has no name-lookup value yet; in those cases, I'd suggest using the code *as the name*, and indicating this in the documentation.)

**Comment by declanrjb** [comment]
Ok, implemented all of these suggestions, and updated the documentation to reflect them. Also implemented a suggestion of my own: collapsing cols STAT_RSON_1 through 5 to a comma separated list contained in a single column called Status_Reason. Admittedly this is a modification of the original data, but offers significant savings in cell count (dropping a whole 5 columns), and I think if clearly explained in the docs (I've added a start) presents the same information in a much more efficient way. Let me know what you think.

Unfortunately this still doesn't quite meet the goal, we stand at:
2000-2009 chunk: 109.3 MB
2010-2019 chunk: 127 MB
2020-2024 chunk: 54.3 MB (only one under 100)

Included a zip version to get it hosted for now but that's not a long-term solution. If anyone else has ideas for reducing the size further (other than splitting into more chunks), please chime in.

**Comment by jsvine** [comment]
Thanks! And hmmm, what if we split into five-year chunks!?

Also, collapsing the status reason codes into a single column makes sense to me. (And probably also helpful for people who want to search across all the enumerated reasons at once.)

**Comment by declanrjb** [comment]
That did the trick! Committing five year chunks now
