### ISSUE TITLE
Removing `comptime`

### ISSUE THREAD

**Issue by jsvine** [declanrjb/dlp-inmate-complaints#2]
`comptime` (`Comptime_Days` in the current draft) is a derived column and I think can be removed. Via the DLP documentation:

> The BOP description appears to be mistaken; averages do not appear to play a role in the creation of this column. Rather, for closed filings (CDSTATUS = “CLD”, “CLG”, or ”CLO”), this value is exactly the number of days between sitdtrcv and sdtstat. For filings with CDSTATUS of “ACC” or “REJ”, this value is null.

**Comment by declanrjb** [comment]
Complete
