### ISSUE TITLE
Changing `NA` to an empty value

### ISSUE THREAD

**Issue by jsvine** [declanrjb/dlp-inmate-complaints#3]
For consistency across programming tools, fidelity to the original records, and some (admittedly minor) size savings, I'd suggest writing null values as empty values rather than the R-default `NA`.

**Comment by declanrjb** [comment]
Changed export command to write NAs as blank string ''. Let me know if that's sufficient for the purposes you're describing

**Comment by jsvine** [comment]
That should do the trick, but let's make sure they're being written as, e.g., `,,` rather than `,'',`

**Comment by declanrjb** [comment]
Yes, just went through raw text on the latest export and can confirm that's the case
