### ISSUE TITLE
Add source of coordinates to facility-locations.csv

### ISSUE THREAD

**Issue by jsvine** [declanrjb/dlp-inmate-complaints#4]
From [the code](https://github.com/declanrjb/dlp-inmate-complaints/blob/main/fac_clean.R), it looks like it's trying a couple of different geocoding sources. For provenance-tracking's sake, it'd be nice to add a column to `facility-locations.csv` that indicates the source of the coordinates included.

**Comment by declanrjb** [comment]
Resolved, coords provenance now under facility-locations.csv$Fac_Coords_Method
