### ISSUE TITLE
Consider using BOP's own facility-coordinate data

### ISSUE THREAD

**Issue by jsvine** [declanrjb/dlp-inmate-complaints#5]
It appears that BOP has official-seeming geocoordinates for its facilities in the source code here: https://www.bop.gov/locations/map.jsp

E.g.: 

---

<img width="639" alt="Screenshot 2024-07-22 at 5 06 22 PM" src="https://github.com/user-attachments/assets/a4451c26-1e99-4bc6-a779-b02b8d5d3c3b">

---

It might be worth pulling that data in — and, if it looks reliable — favoring it over the address-geocoding results when available.

**Comment by declanrjb** [comment]
Ok, resolved. Initial data processing step is a little messy (I just pasted that code from the header of the BOP site into a JSON parser and cleaned up the resulting CSV in R), but it works. Will write some better documentation as to where/how that data was obtained tomorrow

**Comment by declanrjb** [comment]
Code comments for obtaining BOP official location data added to code/fac_clean.R

**Comment by jsvine** [comment]
Nice!
