### ISSUE TITLE
Consider using Parquet raw-data file instead of CSV

### ISSUE THREAD

**Issue by jsvine** [declanrjb/dlp-inmate-complaints#7]
The [Parquet version of the raw data](https://drive.google.com/drive/folders/1XLMTvKsWs4I3MCi7bkF5_SyL5bb3lGbJ) is considerably smaller than the CSV file (24mb vs. 192mb), and could be committed directly to the repo, simplifying its reproducibility.

**Comment by declanrjb** [comment]
Parquet files added

**Comment by jsvine** [comment]
Ah, sorry, I wasn't as clear as I could have been: I meant replacing `raw_data/complaint-filings.csv` (uncommitted because it's too large) with the Parquet version, so that the raw source data can be committed, making the pipeline reproducible without having to manually download any files.

Re. the clean/output files as Parquet: Doesn't hurt to have added them in the repo!

**Comment by declanrjb** [comment]
Got it, I'll get that changed now

**Comment by declanrjb** [comment]
Done
